#!/usr/bin/env python3
"""
Generate a Liberty (.lib) timing file from ML-predicted delays.

For each cell we emit a cell_rise / cell_fall NLDM table indexed by
(input_slew, output_cap). Delay values come from the trained ML surrogate via
TimingInference, demonstrating ML-assisted library characterization.

Run:  python data/gen_liberty.py
"""
from __future__ import annotations

import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
sys.path.insert(0, str(ROOT / "ml"))
from inference import TimingInference  # noqa: E402

LIB_DIR = ROOT / "data" / "liberty"
LIB_DIR.mkdir(parents=True, exist_ok=True)

# NLDM template axes
INDEX_SLEW = [0.01, 0.05, 0.10, 0.20, 0.40]          # ns (input transition)
INDEX_CAP = [0.001, 0.005, 0.010, 0.020, 0.050]      # pF (output load)

CELLS = [
    {"name": "sky130_inv_x1", "cell": "inv", "drive": 1,
     "inpin": "A", "outpin": "Z", "sense": "negative_unate"},
    {"name": "sky130_nand2_x1", "cell": "nand2", "drive": 1,
     "inpin": "A", "outpin": "Z", "sense": "negative_unate"},
    {"name": "sky130_dff_x1", "cell": "dff", "drive": 1,
     "inpin": "CLK", "outpin": "Q", "sense": "non_unate"},
]


def fmt_index(vals):
    return ", ".join(f"{v:g}" for v in vals)


def delay_table(eng, cell, drive, rise: bool):
    """Return rows[5] x cols[5] of delay in ns; rows=slew, cols=cap."""
    rows = []
    for slew in INDEX_SLEW:
        row = []
        for cap_pf in INDEX_CAP:
            cload_ff = cap_pf * 1000.0
            r = eng.predict(cell=cell, vdd=1.80, temp=27,
                            cload_ff=cload_ff, drive=drive, corner="tt")
            # crude slew sensitivity: longer input slew adds ~ slew/4 of delay
            base = r["tpLH_ps"] if rise else r["tpHL_ps"]
            d_ps = base + (slew * 1000.0) * 0.25
            row.append(d_ps / 1000.0)        # ps -> ns
        rows.append(row)
    return rows


def fmt_values(rows):
    body = []
    for r in rows:
        body.append('          "' + ", ".join(f"{v:.4f}" for v in r) + '"')
    return ", \\\n".join(body)


def emit_timing(eng, c):
    rise = delay_table(eng, c["cell"], c["drive"], rise=True)
    fall = delay_table(eng, c["cell"], c["drive"], rise=False)
    return f"""      timing() {{
        related_pin : "{c['inpin']}";
        timing_sense : {c['sense']};
        timing_type : combinational;
        cell_rise(delay_template_5x5) {{
          index_1("{fmt_index(INDEX_SLEW)}");
          index_2("{fmt_index(INDEX_CAP)}");
          values( \\
{fmt_values(rise)} );
        }}
        cell_fall(delay_template_5x5) {{
          index_1("{fmt_index(INDEX_SLEW)}");
          index_2("{fmt_index(INDEX_CAP)}");
          values( \\
{fmt_values(fall)} );
        }}
      }}"""


def emit_cell(eng, c):
    return f"""  cell({c['name']}) {{
    area : 1.0;
    pin({c['inpin']}) {{ direction : input; capacitance : 0.002; }}
    pin({c['outpin']}) {{
      direction : output;
      max_capacitance : 0.050;
{emit_timing(eng, c)}
    }}
  }}"""


def main():
    eng = TimingInference()
    cells_txt = "\n".join(emit_cell(eng, c) for c in CELLS)
    lib = f"""/* Liberty timing file generated by ML-assisted characterization */
/* Process: sky130 (proxy), Tool: custom ML predictor v1.0          */
/* Corner: tt, 1.80V, 27C. Delays in ns, predicted by PyTorch MLP.  */

library(sky130_ml_char) {{
  technology(cmos);
  delay_model : table_lookup;
  time_unit : "1ns";
  voltage_unit : "1V";
  current_unit : "1mA";
  capacitive_load_unit(1, pf);
  leakage_power_unit : "1nW";
  nom_voltage : 1.80;
  nom_temperature : 27.0;
  nom_process : 1.0;

  lu_table_template(delay_template_5x5) {{
    variable_1 : input_net_transition;
    variable_2 : total_output_net_capacitance;
    index_1("{fmt_index(INDEX_SLEW)}");
    index_2("{fmt_index(INDEX_CAP)}");
  }}

{cells_txt}
}}
"""
    out = LIB_DIR / "sky130_ml_char.lib"
    out.write_text(lib)
    print(f"[gen_liberty] wrote {out}  ({len(lib.splitlines())} lines)")


if __name__ == "__main__":
    main()
